"$schema" = 'https://starship.rs/config-schema.json'

# Configures the format of the prompt.
format = """
$os\
$username\
$directory\
${custom.dir_tail}\
$git_branch\
$fill\
$c\
$dotnet\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$elixir\
$elm\
$gradle\
$julia\
$nim\
$scala\
$time\
$battery\
$line_break\
$character"""

# Sets the palette to "one_dark".
palette = 'one_dark'

# Sets the colors of the "one_dark" palette.
[palettes.one_dark]
mono0 = '#d7dae0' # terminal white, from the One Dark Pro VSCode theme.
mono1 = '#abb2bf' # syntax_fg.
mono2 = '#828997'
mono3 = '#5c6370'
mono4 = '#3f4451' # terminal black, from the One Dark Pro VSCode theme.
color_red0 = '#e06c75'
color_red1 = '#be5046'
color_red2 = '#d31334'
color_green = '#98c379'
color_yellow = '#e5c07b'
color_blue = '#61afef'
color_purple = '#c678dd'
color_cyan = '#56b6c2'
color_orange = '#d19a66'
syntax_fg = '#abb2bf'
syntax_bg = '#282c34'
color_bg2 = '#665c54'
syntax_gutter = '#647382'
syntax_accent = '#528cff'

# Module that displays the current OS.
[os]
disabled = false # Disabled by default
style = "fg:mono0 bg:color_red1"
format = '[ $symbol ]($style)'

# Sets custom symbols for each OS.
[os.symbols]
Alpine = ""
Amazon = ""
Android = "󰀲"
Arch = ""
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
FreeBSD = "󰣠"
Gentoo = "󰣨"
Illumos = ""
Linux = "󰌽"
Macos = "󰍲"
Manjaro = "󱘊"
Mint = "󰣭"
NixOS = "󱄅"
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Redox = "R"
Solus = ""
SUSE = ""
Ubuntu = "󰕈"
Unknown = ""
Windows = "󰍲"

# Module that displays the current username.
[username]
show_always = true
style_user = "bold fg:mono0 bg:color_red1"
style_root = "bold fg:mono0 bg:color_purple"
format = '[$user ]($style)'

# Module that displays the current directory.
[directory]
style = "bold fg:syntax_bg bg:color_green"
format = "[ $path ]($style)"
truncation_length = 1
truncate_to_repo = false

[custom.dir_tail]
when = ''' ! git rev-parse --is-inside-work-tree >/dev/null 2>&1 '''
command = "true"
format = ""

# Module that displays the current git branch.
[git_branch]
symbol = ""
style = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:syntax_bg bg:color_yellow)]($style)'

# Language specific modules
[nodejs]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[c]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[dotnet]
symbol = "󰪮"
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[rust]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[golang]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[php]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[java]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[kotlin]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[haskell]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[python]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[elixir]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[elm]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[gradle]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[julia]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[scala]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

# Module that fills the space between the left and right segments.
[fill]
symbol = "█"
style = 'mono4'

# Module that displays the time.
[time]
disabled = false # Disabled by default
use_12hr = false # Disable for 24h format without seconds
style = "bg:color_orange"
format = '[[ 󰥔 $time ](fg:syntax_bg bg:color_orange)]($style)'

# Module that displays the battery level and status.
[battery]
format = '[ $symbol $percentage ]($style)'

# Battery symbols and colors for each threshold.
[[battery.display]]
threshold = 10
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰁺"
charging_symbol = "󰢜"

[[battery.display]]
threshold = 20
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰁻"
charging_symbol = "󰂆"

[[battery.display]]
threshold = 30
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰁼"
charging_symbol = "󰂇"

[[battery.display]]
threshold = 40
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰁽"
charging_symbol = "󰂈"

[[battery.display]]
threshold = 50
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰁾"
charging_symbol = "󰢝"

[[battery.display]]
threshold = 60
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰁿"
charging_symbol = "󰂉"

[[battery.display]]
threshold = 70
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰂀"
charging_symbol = "󰢞"

[[battery.display]]
threshold = 80
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰂁"
charging_symbol = "󰂊"

[[battery.display]]
threshold = 90
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰂂"
charging_symbol = "󰂋"

[[battery.display]]
style = "bold bg:color_green fg:syntax_bg"
discharging_symbol = "󰁹"
charging_symbol = "󰂅"
threshold = 100

# New line character
[character]
success_symbol = '[\$](bold fg:mono0)'
error_symbol = '[\$](bold fg:color_red1)'
vimcmd_symbol = '[\$](bold fg:syntax_accent)'
vimcmd_replace_one_symbol = '[\$](bold fg:color_purple)'
vimcmd_replace_symbol = '[\$](bold fg:color_purple)'
vimcmd_visual_symbol = '[\$](bold fg:color_yellow)'